name: Testing

on: push

env:
  VITE_API_URL: http://localhost:4000/

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v4

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
